# Change baseurl before deploy
baseurl = "https://lib.sci-adv.cc"
languageCode = "zh-cn"
paginate = 25
title = "科学ADV图书馆"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "en"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true


buildFuture = true
enableGitInfo = true
FootnoteReturnLinkContents = "↩"

[menu]
[[menu.main]]
    name = "科A资源站"
    url = "http://drive.sci-adv.cc"
    weight = 3
    identifier = "server"
    [menu.main.params]
        icon = "rss"
        newTab = true


[sitemap]
  changeFreq = ''
  disable = false
  filename = 'sitemap.xml'
  priority = -1
